image:
  repository: "749291336608.dkr.ecr.us-east-1.amazonaws.com/nim-shim" # container location
  tag: "medical_imaging_vista3d"
model:
  name: vista3d
  openaiPort: 8008
resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
persistence:
  enabled: false
  size: 30Gi
tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
readinessProbe:
  enabled: true
  path: /health/ready  # correct for LLM container
livenessProbe:
  enabled: true
  path: /health/live  # correct for LLM container
startupProbe:
  enabled: true
  path: /health/ready
service:
  openaiPort: 8008
replicaCount: 2
